branches:
  # don't attempt to build branches intented for windows builds
  except:
    - /.*win.*/

os: linux
dist: trusty
language: generic

install:
    # Install Miniconda.
    - echo `pwd`
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /home/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true

script:
  - echo `pwd`
  - ls -lah

  - conda install -y-q jinja2 pygit2 click pyyaml
  - git clone https://github.com/apache/arrow ../arrow
  #
  # - pushd arrow/dev/tasks/conda-recipes
  # - python crossbow.py
