jobs:
- job: linux
  pool:
    vmImage: ubuntu-18.04
  timeoutInMinutes: 360
  steps:
    # for deployment
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: 'python=3.6'

    # for building the linux packages
    - task: UseRubyVersion@0
      inputs:
        addToPath: true

    - script: |
        git clone --no-checkout origin arrow
        git -C arrow fetch -t origin linux-packaging-azure
        git -C arrow checkout FETCH_HEAD
        git -C arrow submodule update --init --recursive
      displayName: Clone arrow

    - script: |
        pushd arrow/dev/tasks/linux-packages
        rake version:update
        rake dist
        rake yum:build CENTOS_VERSIONS=6
        popd

    # Using github release tries to find a common ancestor between the
    # currently pushed tag and the latest tag of the github repository
    # (don't know why).
    # The tag upload took 43 minutes because of this scan, so use an
    # alternative upload script.
    - script: |
        conda install -y --file arrow/ci/conda_env_crossbow.txt
        python crossbow.py upload-assets \
          --sha build-672-azure-centos-6 \
          --tag build-672-azure-centos-6 \
        --pattern "**/*.rpm"
        env:
        CROSSBOW_GITHUB_REPO: $(Build.Repository.Name)
        CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
      displayName: Upload packages as a GitHub release
      workingDirectory: arrow/dev/tasks