jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 360

  variables:
    CONFIG: linux_python3.7
    UPLOAD_PACKAGES: False
    DOCKER_IMAGE: condaforge/linux-anvil-comp7

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
      git clone --no-checkout https://github.com/kszucs/arrow arrow
      git -C arrow fetch -t https://github.com/kszucs/arrow crossbow-azure
      git -C arrow checkout 9c3415ae7c34af49fa581a9cf21641f9c43fd123

  - script: CI=azure ./run_docker_build.sh
    displayName: Run docker build
    workingDirectory: arrow/dev/tasks/conda-recipes