jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 360
  steps:
    # for building the linux packages
    - task: UseRubyVersion@0
      inputs:
        addToPath: true

    - script: |
        git clone --no-checkout https://github.com/apache/arrow arrow
        git -C arrow fetch -t https://github.com/apache/arrow refs/pull/5296/merge
        git -C arrow checkout FETCH_HEAD
        git -C arrow submodule update --init --recursive
      displayName: Clone arrow

    - script: |
        pushd arrow/dev/tasks/linux-packages
        rake version:update
        rake dist
        rake apt:build APT_TARGETS=ubuntu-xenial
        popd
      displayName: Build

    # Using github release tries to find a common ancestor between the
    # currently pushed tag and the latest tag of the github repository
    # (don't know why).
    # The tag upload took 43 minutes because of this scan, so use an
    # alternative upload script.
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: 'click github3.py jinja2 jira pygit2 ruamel.yaml setuptools_scm toolz'
        installOptions: '-c conda-forge'
        updateConda: false
    - script: |
        python arrow/dev/tasks/crossbow.py \
          --queue-path . \
          --queue-remote https://github.com/ursa-labs/crossbow \
          upload-artifacts \
          --sha ursabot-152-azure-ubuntu-xenial \
          --tag ursabot-152-azure-ubuntu-xenial \
          --pattern "**/*.deb"
        
          --pattern "**/*.dsc"
        
          --pattern "**/*.debian.tar.xz"
        
          --pattern "**/*.orig.tar.gz"
        
      env:
        CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
      displayName: Upload packages as a GitHub release