jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 360

  variables:
    CONFIG: linux_python3.6
    ARROW_VERSION: 0.13.0.dev518
    DOCKER_IMAGE: condaforge/linux-anvil-comp7
    UPLOAD_PACKAGES: False

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    displayName: Configure binfmt_misc
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))

  - script: |
      git clone --no-checkout https://github.com/apache/arrow arrow
      git -C arrow fetch -t https://github.com/apache/arrow refs/pull/4649/merge
      git -C arrow checkout eb6cdcadc2138a0bf77f570a3c7f2dfd30a76b54
    displayName: Clone arrow

  - script: CI=azure ./run_docker_build.sh
    displayName: Run docker build
    workingDirectory: arrow/dev/tasks/conda-recipes

  # Using github release tries to find a common ancestor between the currently
  # pushed tag and the latest tag of the github repository (don't know why).
  # The tag upload took 43 minutes because of this scanning, so use an
  # alternative upload script.
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - script: |
      pip3 install github3-py click
      python upload-assets.py \
        --sha ursabot-61-azure-conda-linux-gcc-py36 \
        --tag ursabot-61-azure-conda-linux-gcc-py36 \
        --pattern "conda-recipes/build_artifacts/*.tar.bz2"
    env:
      CROSSBOW_GITHUB_REPO: $(Build.Repository.Name)
      CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
    displayName: Upload packages as a GitHub release
    workingDirectory: arrow/dev/tasks