jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 360
  steps:
    # for building the linux packages
    - task: UseRubyVersion@0
      inputs:
        addToPath: true

    - script: |
        git clone --no-checkout https://github.com/apache/arrow arrow
        git -C arrow fetch -t https://github.com/apache/arrow refs/pull/5296/merge
        git -C arrow checkout FETCH_HEAD
        git -C arrow submodule update --init --recursive
      displayName: Clone arrow

    # We can remove this with binfmt-support 2.1.7 or later and
    # qemu-user-static 2.12 or later. It requires Debian buster or later,
    # or Ubuntu 18.10 or later.
    - script: |
        sudo apt install -y qemu-user-static unar
        wget http://archive.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-static_3.1+dfsg-2ubuntu3.4_amd64.deb
        unar *.deb
        rm *.deb
        pushd qemu-user-static*
        unar data.*
        for arm64_image in ../arrow/dev/tasks/linux-packages/apt/*-arm64/; do
          cp data/usr/bin/qemu-aarch64-static ${arm64_image}
        done
        popd
      displayName: Prepare qemu-user-static

    - script: |
        pushd arrow/dev/tasks/linux-packages
        rake version:update
        rake dist
        rake apt:build APT_TARGETS=debian-stretch-arm64
        popd
      displayName: Build

    # Using github release tries to find a common ancestor between the
    # currently pushed tag and the latest tag of the github repository
    # (don't know why).
    # The tag upload took 43 minutes because of this scan, so use an
    # alternative upload script.
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: 'click github3.py jinja2 jira pygit2 ruamel.yaml setuptools_scm toolz'
        installOptions: '-c conda-forge'
        updateConda: false
    - script: |
        python arrow/dev/tasks/crossbow.py \
          --queue-path . \
          --queue-remote https://github.com/ursa-labs/crossbow \
          upload-artifacts \
          --pattern "**/*.deb" \
          --pattern "**/*.dsc" \
          --pattern "**/*.debian.tar.xz" \
          --pattern "**/*.orig.tar.gz" \
          --sha ursabot-159-azure-debian-stretch-arm64 \
          --tag ursabot-159-azure-debian-stretch-arm64
      env:
        CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
      displayName: Upload packages as a GitHub release