version: 2

jobs:
  build:
    machine: true
    steps:
      - run: echo "OK"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /.*-circle/
