# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - run: docker -v
      - run: docker-compose -v
      - run: git clone --no-checkout https://github.com/fsaintjacques/arrow arrow
      - run: git -C arrow fetch -t https://github.com/fsaintjacques/arrow ARROW-6448-fix-crossbow-notif
      - run: git -C arrow checkout FETCH_HEAD
      - run: git -C arrow submodule update --init --recursive
      - run: |
          pushd arrow
            docker-compose build cpp
            docker-compose build python
            docker-compose build lint
            docker-compose run clang-format
          popd
      - zulip/status:
           stream: crossbow
           fail_only: true
           topic: CircleCI Activity

orbs:
   zulip: ponylang/zulip@1.0.2
workflows:
  version: 2
  build:
    jobs:
      - build