name: Submit

on:
  # remove once they are working properly
  pull_request:
    paths:
      - '.github/workflows/nightly_submit.yml'
  schedule:
    - cron: '0 6 * * *'

jobs:

  nightly-submit:
    name: Submit Nightly Builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crossbow
        uses: actions/checkout@v1
        with:
          path: crossbow
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          repository: "apache/arrow"
          path: arrow
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          conda-channels: "conda-forge"
      - name: Install Dependencies
        shell: bash
        run: conda install -y --file arrow/ci/conda_env_crossbow.txt
      - name: Submit Nightlies
        shell: bash
        env:
          CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
        run: |
          arrow/dev/tasks/crossbow.py submit \
            --job-prefix nightly-$(date -I) \
            --group nightly \
            --dry-run